### PR TITLE
Prevent Rails 4 from setting env to test when running as resque-pool

### PR DESCRIPTION
**Pull request by brucek**
Fixes https://github.com/nevans/resque-pool/issues/158

### CODE REVIEW

**Comment by brucek** [comment]
I didn't see a straightforward way to test this separately, but all feature scenarios failed when there was any problem here.

**Comment by alfredoreduarte** [comment]
I'm having the exact same problem that this solves. Has it been merged yet? 😱

**Comment by codyrobbins** [comment]
I too was bitten by this so this would be a great addition.

**Comment by brucek** [comment]
Hey @nevans, just pinging to see if there is any chance you might take a look / merge this?  Thanks

**Pull request merged**
