### PR TITLE
bump ruby requirement and stop using downgraded mustache

### PR DESCRIPTION
**Pull request by grosser**
@nevans

### CODE REVIEW

**Comment by nevans** [comment]
Looks like the build is failing...  We should either (in order of increasing preference):
 1. keep cucumber pinned to an old version by committing a Gemfile.lock.
 2. Or keep cucumber `~>` an old version in the gemspec.
 3. Or update the cucumber features to not crash with the latest versions of cucumber and/or aruba.
 4. Or... we don't really need cucumber anyway (it's not like I'm generating relishapp documentation from it).  It was just something I was toying around with back in early 2011.  I'd be completely fine if someone converted the cucumber specs to modern rspec (using modern aruba or something similar).

**Comment by grosser** [comment]
2 it is ;)

**Comment by nevans** [comment]
I have mixed feelings about leaving 1.9.3 behind.

On the one hand, I sympathize with those poor folks who are stuck with huge hideous legacy apps that they aren't given the necessary time to upgrade to modern ruby.  I've been there.  No fun.
On the other hand, keyword arguments!!!1  Use them _everywhere_! :wink:

The only reason we are using `mustache` is for `ronn`.  The only reason we're using `ronn` is for man pages.  The man pages are _very_ outdated.  So just deleting the man pages and moving those docs into either the README.md or some other markdown file or github wiki or even into rdoc makes them more likely to actually get used and updated.  And then we could drop `ronn` (and `mustache`) entirely.

Alternatively, if we are going to keep the man pages (and eventually update them!), is there any reason not to do [what bundler does](https://github.com/bundler/bundler/blob/77c265128bce9078d053f0e96e4bf6f70f8470c8/bundler.gemspec#L20) and `add_development_dependency "mustache",   "0.99.6"` in the gemspec?

**Comment by grosser** [comment]
updated ... kind of the same but a little better I guess ...

**Pull request merged**
